### PR TITLE
add feature fontSize

### PR DESCRIPTION
**Pull request by chrissd23**
add fontSize values between 1-7

### CODE REVIEW

**Comment by wasabeef** [comment]
@chrissd23 

great!

**Comment by chrissd23** [comment]
Thx :) 

When will you release the next version ? @wasabeef

**Comment by chrissd23** [comment]
Thx @wasabeef

**Comment by wasabeef** [comment]
@chrissd23 
(๑•̀ㅂ•́)و✧ GJ

**Pull request merged**
